SLEEP_TIME_SEC = 10
GPIO_PATIENT_OUTPUT_PIN = 24
GPIO_PATIENT_INPUT_PIN = 23
ALARM_NOISE= "/usr/share/scratch/Media/Sounds/Human/Scream-male2.mp3"
GPIO_NURSE_OUTPUT_PIN = 16
GPIO_NURSE_INPUT_PIN = 25
LIGHT_DELAY = 3
BUTTON_DELAY = 5