SLEEP_TIME_SEC = 10
GPIO_PATIENT_OUTPUT_PIN = 12 #     gpio 18 
GPIO_PATIENT_INPUT_PIN = 10 #     rxd / gpio 15
ALARM_NOISE= "/usr/share/scratch/Media/Sounds/Human/Scream-male2.mp3"
GPIO_NURSE_OUTPUT_PIN = 21 #     miso / gpio 9 
GPIO_NURSE_INPUT_PIN = 19 #     mosi / gpio 10 
LIGHT_DELAY = 3 # seconds
BUTTON_DELAY = 5
IDLE = 0 # Nobody's waiting for anything
WAITING = 1 # Patient is
# STATE=.